name: Build & Push Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # üß± Create ECR Repositories if Not Exists
      - name: Create ECR Repositories
        run: |
          for repo in ecommerce-backend ecommerce-frontend ecommerce-seller; do
            aws ecr describe-repositories --repository-names $repo >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name $repo
          done

      # üîñ Set Image Tag (Git Commit SHA)
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # üê≥ Build & Push Backend
      - name: Build & Push Backend Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecommerce-backend

          docker build -t ecommerce-backend ./Backend
          docker tag ecommerce-backend:latest $IMAGE_URI:latest
          docker tag ecommerce-backend:latest $IMAGE_URI:${IMAGE_TAG}

          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${IMAGE_TAG}

      # üê≥ Build & Push Frontend
      - name: Build & Push Frontend Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecommerce-frontend

          docker build -t ecommerce-frontend ./Frontend
          docker tag ecommerce-frontend:latest $IMAGE_URI:latest
          docker tag ecommerce-frontend:latest $IMAGE_URI:${IMAGE_TAG}

          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${IMAGE_TAG}

      # üê≥ Build & Push Seller
      - name: Build & Push Seller Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecommerce-seller

          docker build -t ecommerce-seller ./Seller
          docker tag ecommerce-seller:latest $IMAGE_URI:latest
          docker tag ecommerce-seller:latest $IMAGE_URI:${IMAGE_TAG}

          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${IMAGE_TAG}
